services:
  - type: web
    name: vetting-app
    env: docker
    repo: https://github.com/pmendyk-crypto/vetting-app.git
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    instanceSize: starter
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: vetting-db
          property: connectionString

databases:
  - name: vetting-db
    databaseName: vetting_app
    plan: free
